spring:
  application:
    name: patients-api
  datasource:
    url: jdbc:mysql://localhost:3307/imss-bienestar
    username: root
    password:
 
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update